# docker-compose.yml
version: '3'
services:
  spider:
    build: .
    volumes:
      - .:/app
    depends_on:
      - chrome
    networks:
      - my_network
  chrome:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"
    networks:
      - my_network
networks:
  my_network:
    driver: bridge